#!/bin/bash

# deps check
dependencies=("akory" "xxd" "jq" "git" "xclip" "corkscrew" "gedit")
for dep in "${dependencies[@]}"; do
    if ! command -v "$dep" > /dev/null 2>&1; then
        echo "error: '$dep' is not installed !"
        exit 1
    fi
done
akory -d 0.02 "check dependencies ... [done]"

# download ha-proxy from repository
curl https://raw.githubusercontent.com/RajaRakoto/ha-proxy/master/ha-proxy > ha-proxy
akory -d 0.02 "download ha-proxy ... [done]"

# create env
echo -e "
# files
HA_VSCODE="$HOME/.config/Code - Insiders/User/settings.json"
HA_GITCONFIG="$HOME/.gitconfig"
HA_SSHAUTH="$HOME/.ssh/auth"
HA_SSHCONFIG="$HOME/.ssh/config"
HA_ENV="$HOME/.ha_env"

# config
HA_PROXY="0.0.0.0"
HA_PORT=8080
HA_SSH_PORT=8080
HA_USERNAME="user"
HA_PASSWORD="password"
" | tee .ha_env > /dev/null
akory -d 0.02 "create .ha_env ... [done]"

# set access
chmod 600 .ha_env
sudo chmod a+rx ha-proxy
akory -d 0.02 "set access ... [done]"

# to exact path
mv .ha_env $HOME
sudo mv ha-proxy /usr/local/bin/
akory -d 0.02 "INSTALLATION COMPLETED ! ... [done]"

# test
sleep 1
ha-proxy --version